imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
#based on https://vincent.composieux.fr/article/test-your-doctrine-repository-using-a-sqlite-database
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:  pdo_sqlite
                user:    test
                path:    %kernel.root_dir%/sqlite.db.cache
                #memory: true
                charset: utf8
