imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: cs

framework:
    #esi: ~
    translator: { fallbacks: [en] }

    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        
# Vich
vich_uploader:
    db_driver: orm
    mappings:
        event_image:
            uri_prefix:         /images/events
            upload_destination: '%kernel.root_dir%/../web/images/events'
            namer:
                service: vich_uploader.namer_uniqid
    

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email: 
        address:        improsmecka@gmail.com
        sender_name:    Improsmečka
    registration:
        form:
            type: AppBundle\Form\RegistrationType

easy_admin:
    entities:        
        Event:
            class: AppBundle\Entity\Event
            list:
                fields: ['user', 'faction', 'description', 'valid', 'points', 'image']
                   #- { property: 'image', type: 'image', base_path: '%kernel.root_dir%/../web/images/events' }
            #form:
            #    fields:
            #        - { property: 'imageFile', type: 'vich_image' }
                   
        User:
            class: AppBundle\Entity\User